apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{KUBER_DP_NAME}}
  namespace: stand-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{KUBER_DP_NAME}}
    spec:
      containers:
      - name: nginx
        image: {{KUBER_IMAGE_TAG}}
        ports:
        - name: dp-listened
          protocol: TCP
          containerPort: {{PORT}}
        env:
        - name: LISTENED_PORT
          value: "{{PORT}}"
        - name: PROXYED_HOST
          value: "{{PROXYED_HOST}}"
        - name: PROXYED_PORT
          value: "{{PROXYED_PORT}}"
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - {{DNS_IP}}