{
 "title": "Demo stand cluster",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU usage (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(irate(container_cpu_usage_seconds_total{container_name=~\"(stand|demo)-.*\"}[1m]) * 100, 0.0001)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Containers status",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "container_start_time_seconds{container_name=~\"(stand|demo)-.*\"} * 1000"
    },
    {
     "expr": "count(resets(container_start_time_seconds{container_name=~\"(stand|demo)-.*\"}[30d])) by (container_name, instance)"
    },
    {
     "expr": "container_memory_usage_bytes{container_name=~\"(stand|demo)-.*\"} / (1024^3)"
    }
   ]
  },
  {
   "title": "Nodes status",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "machine_cpu_cores{instance!=\"kubeadm.ipavlov.mipt.ru\"}"
    },
    {
     "expr": "machine_memory_bytes{instance!=\"kubeadm.ipavlov.mipt.ru\"} / (1024^3)"
    }
   ]
  }
 ]
}