{
 "title": "Metrics",
 "tags": [ "metrics" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(up{container_name=\"socialservice\"}, kubernetes_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "request latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_latency_seconds_bucket{kubernetes_name=\"$app\"}[5m])) by (le, endpoint, target_name))",
     "legendFormat": "endpoint={{endpoint}}, pod={{target_name}}"
    }
   ]
  },
  {
   "title": "rps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_count_total{kubernetes_name=\"$app\"}[5m])) by (endpoint, target_name)",
     "legendFormat": "endpoint={{endpoint}}, pod={{target_name}}"
    }
   ]
  },
  {
   "title": "requests inflight",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_in_progress{kubernetes_name=\"$app\"}) by (endpoint, target_name)",
     "legendFormat": "endpoint={{endpoint}}, pod={{target_name}}"
    }
   ]
  },
  {
   "title": "error rps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_count_total{kubernetes_name=\"$app\",code!~\"2..\"}[5m])) by (code,endpoint, target_name)",
     "legendFormat": "endpoint={{endpoint}}, pod={{target_name}}, code={{code}}"
    }
   ]
  }
 ]
}