apiVersion: v1
kind: Service
metadata:
  name: stand-chatbot-en-proxy-lb
  namespace: stand-demo
spec:
  selector:
    app: stand-chatbot-en-proxy-dp
  type: LoadBalancer
  externalIPs:
  - 10.11.1.251
  ports:
  - name: lb-listened
    protocol: TCP
    port: 7018
    targetPort: dp-listened