apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-terminus-db-dp
  namespace: stand-demo
spec:
  selector:
    matchLabels:
      app: graph-terminus-db-dp
  replicas: 1
  template:
    metadata:
      labels:
        app: graph-terminus-db-dp
    spec:
      containers:
      - name: terminus
        image: terminusdb/terminusdb-server:v10.1.10
        ports:
        - name: dp-terminus
          protocol: TCP
          containerPort: 6363
        volumeMounts:
        - name: volume-gdb-data
          mountPath: /app/terminusdb/storage
        - name: volume-podinfo
          mountPath: /etc/podinfo
          readOnly: false
        env:
        - name: POD_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: FULL_MODEL_NAME
          value: 'graph_terminus_db'
        envFrom:
          - secretRef:
              name: gdb-secret
      volumes:
      - name: volume-gdb-data
        persistentVolumeClaim:
          claimName: gdb-hostpath-pvc
      - name: volume-podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.11.1.254
