apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-hostpath-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: prometheus-hostpath-sc
  resources:
    requests:
      storage: 8Gi
