apiVersion: v1
kind: Service
metadata:
  name: {{KUBER_LB_NAME}}
  namespace: stand-demo
spec:
  selector:
    app: {{KUBER_DP_NAME}}
  type: LoadBalancer
  externalIPs:
  - {{CLUSTER_IP}}
  ports:
  - name: lb-routerbot
    protocol: TCP
    port: {{CLUSTER_PORT}}
    targetPort: dp-routerbot
  - name: lb-mongo
    protocol: TCP
    port: {{CLUSTER_MONGO_PORT}}
    targetPort: dp-mongo
  - name: lb-ssh
    protocol: TCP
    port: {{CLUSTER_SSH_PORT}}
    targetPort: dp-ssh