apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-hostpath-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: loki-hostpath-sc
  resources:
    requests:
      storage: 10Gi
