dp_base_cpu:
  - dp_base_cpu_test

stand:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_cn
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru
  - stand_chatbot_en_proxy

socialbot:
  - socialbot_alice
  - socialbot_animals_tfidf_retrieval
  - socialbot_asr
  - socialbot_blacklisted_words
  - socialbot_book_skill
  - socialbot_book_tfidf_retrieval
  - socialbot_christmas_new_year_skill
  - socialbot_comet_atomic
  - socialbot_comet_conceptnet
  - socialbot_convers_evaluation_selector
  - socialbot_convert_reddit
  - socialbot_coronavirus_skill
  - socialbot_dummy_skill_dialog
  - socialbot_eliza
  - socialbot_emotion_classification
  - socialbot_emotion_skill
  - socialbot_entertainment_tfidf_retrieval
  - socialbot_fashion_tfidf_retrieval
  - socialbot_game_cooperative_skill
  - socialbot_greeting_skill
  - socialbot_intent_catcher
  - socialbot_intent_responder
  - socialbot_meta_script_skill
  - socialbot_misheard_asr
  - socialbot_movie_skill
  - socialbot_movie_tfidf_retrieval
  - socialbot_music_tfidf_retrieval
  - socialbot_ner
  - socialbot_news_api_skill
  - socialbot_oscar_skill
  - socialbot_personal_info_skill
  - socialbot_personality_catcher
  - socialbot_politics_tfidf_retrieval
  - socialbot_program_y
  - socialbot_program_y_dangerous
  - socialbot_program_y_wide
  - socialbot_reddit_ner_skill
  - socialbot_science_technology_tfidf_retrieval
  - socialbot_sentiment_classification
  - socialbot_sentrewrite
  - socialbot_sentseg
  - socialbot_short_story_skill
  - socialbot_small_talk_skill
  - socialbot_sport_tfidf_retrieval
  - socialbot_stop_detect
  - socialbot_superbowl_skill
  - socialbot_tfidf_retrieval
  - socialbot_toxic_classification
  - socialbot_valentines_day_skill
  - socialbot_weather_skill

http_proxy: []

alexaprize_idris_repo:
  - alexaprize_idris_repo_rb
  - alexaprize_idris_repo_rbp
  - alexaprize_idris_repo_rb_dev
  - alexaprize_idris_repo_rbp_dev

toloka_go_bot_dstc2:
  - toloka_go_bot_dstc2_model
  - toloka_go_bot_dstc2_rb
  - toloka_go_bot_dstc2_rbp

agent_nti:
  - agent_nti_v0_2
  - agent_nti_v0_2_mongo_db
  - agent_nti_v0_2_ranking_chitchat_2stage
  - agent_nti_v0_2_chitchat_odqa
  - agent_nti_v0_2_rb
  - agent_nti_v0_2_rbp

push_pull:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_cn
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru
  - stand_chatbot_en_proxy

all:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_cn
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru
  - stand_chatbot_en_proxy
  - alexaprize_idris_repo_rb
  - alexaprize_idris_repo_rbp
  - alexaprize_idris_repo_rb_dev
  - alexaprize_idris_repo_rbp_dev