dp_base_cpu:
  - dp_base_cpu_test

stand:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_cn
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru
  - stand_chatbot_en_proxy

dream:
  - dream_agent
  - dream_tg_agent
  - dream_combined-classification
  - dream_dff-dream-faq-prompted-skill
  - dream_dff-dream-persona-chatgpt-prompted-skill
  - dream_dff-google-api-skill
  - dream_dff-intent-responder-skill
  - dream_entity-detection
  - dream_entity-linking
  - dream_fact-retrieval
  - dream_factoid-qa
  - dream_intent-catcher
  - dream_kbqa
  - dream_ner
  - dream_openai-api-chatgpt
  - dream_openai-api-chatgpt-16k
  - dream_prompt-selector
  - dream_property-extraction
  - dream_ranking-based-response-selector
  - dream_sentence-ranker
  - dream_sentseg
  - dream_text-qa
  - dream_wiki-parser

dream_ru:
  - dream_ru_entity-detection-ru
  - dream_ru_ner-ru
  - dream_ru_dialogrpt-ru
  - dream_ru_dialogpt-ru
  - dream_ru_toxic-classification-ru

http_proxy: []

alexaprize_idris_repo:
  - alexaprize_idris_repo_rb
  - alexaprize_idris_repo_rbp
  - alexaprize_idris_repo_rb_dev
  - alexaprize_idris_repo_rbp_dev

toloka_go_bot_dstc2:
  - toloka_go_bot_dstc2_model
  - toloka_go_bot_dstc2_rb
  - toloka_go_bot_dstc2_rbp

agent_nti:
  - agent_nti_v0_2
  - agent_nti_v0_2_mongo_db
  - agent_nti_v0_2_ranking_chitchat_2stage
  - agent_nti_v0_2_chitchat_odqa
  - agent_nti_v0_2_rb
  - agent_nti_v0_2_rbp

push_pull:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_cn
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru
  - stand_chatbot_en_proxy

all:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_cn
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru
  - stand_chatbot_en_proxy
  - alexaprize_idris_repo_rb
  - alexaprize_idris_repo_rbp
  - alexaprize_idris_repo_rb_dev
  - alexaprize_idris_repo_rbp_dev

entity_extraction:
  - ee_agent
  - ee_wiki_parser
  - ee_entity_extraction

tmp_stand:
  - emotions_xlm_roberta_base
  - insults_xlm_roberta_base
  - intents_distilbert_base_multi
  - sentiments_xlm_roberta_base
  - topics_xlm_roberta_base
  - ner_xlm_roberta_base
