dp_base_cpu:
  - dp_base_cpu_test

stand:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_cn
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru
  - stand_chatbot_en_proxy

dream:
  - dream_agent
  - dream_asr
  - dream_badlisted-words
  - dream_combined-classification
  - dream_comet-atomic
  - dream_comet-conceptnet
  - dream_convers-evaluation-selector
  - dream_convers-evaluator-annotator
  - dream_convert-reddit
  - dream_dff-animals-skill
  - dream_dff-art-skill
  - dream_dff-book-skill
  - dream_dff-bot-persona-skill
  - dream_dff-coronavirus-skill
  - dream_dff-food-skill
  - dream_dff-friendship-skill
  - dream_dff-funfact-skill
  - dream_dff-gaming-skill
  - dream_dff-gossip-skill
  - dream_dff-grounding-skill
  - dream_dff-intent-responder-skill
  - dream_dff-movie-skill
  - dream_dff-music-skill
  - dream_dff-program-y-dangerous-skill
  - dream_dff-program-y-skill
  - dream_dff-program-y-wide-skill
  - dream_dff-science-skill
  - dream_dff-short-story-skill
  - dream_dff-sport-skill
  - dream_dff-template-skill
  - dream_dff-travel-skill
  - dream_dff-weather-skill
  - dream_dff-wiki-skill
  - dream_dialogpt
  - dream_dummy-skill-dialog
  - dream_eliza
  - dream_emotion-skill
  - dream_entity-detection
  - dream_entity-linking
  - dream_entity-storer
  - dream_fact-random
  - dream_fact-retrieval
  - dream_factoid-qa
  - dream_game-cooperative-skill
  - dream_intent-catcher
  - dream_kbqa
  - dream_knowledge-grounding
  - dream_knowledge-grounding-skill
  - dream_masked-lm
  - dream_meta-script-skill
  - dream_midas-classification
  - dream_midas-predictor
  - dream_misheard-asr
  - dream_ner
  - dream_news-api-annotator
  - dream_news-api-skill
  - dream_personal-info-skill
  - dream_personality-catcher
  - dream_sentrewrite
  - dream_sentseg
  - dream_small-talk-skill
  - dream_spacy-nounphrases
  - dream_spelling-preprocessing
  - dream_text-qa
  - dream_topic-recommendation
  - dream_user-persona-extractor
  - dream_wiki-facts
  - dream_wiki-parser

http_proxy: []

alexaprize_idris_repo:
  - alexaprize_idris_repo_rb
  - alexaprize_idris_repo_rbp
  - alexaprize_idris_repo_rb_dev
  - alexaprize_idris_repo_rbp_dev

toloka_go_bot_dstc2:
  - toloka_go_bot_dstc2_model
  - toloka_go_bot_dstc2_rb
  - toloka_go_bot_dstc2_rbp

agent_nti:
  - agent_nti_v0_2
  - agent_nti_v0_2_mongo_db
  - agent_nti_v0_2_ranking_chitchat_2stage
  - agent_nti_v0_2_chitchat_odqa
  - agent_nti_v0_2_rb
  - agent_nti_v0_2_rbp

push_pull:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_cn
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru
  - stand_chatbot_en_proxy

all:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_cn
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru
  - stand_chatbot_en_proxy
  - alexaprize_idris_repo_rb
  - alexaprize_idris_repo_rbp
  - alexaprize_idris_repo_rb_dev
  - alexaprize_idris_repo_rbp_dev