dream_agent:
  BASE_IMAGE: dream-agent
  CLUSTER_PORT: '7019'
  CMD_SCRIPT:
  - sh
  - -c
  - bin/wait && python -m deeppavlov_agent.run agent.pipeline_config=assistant_dists/dream/pipeline_conf.json agent.cors=True
  PORT: 4242
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8a'
dream_tg_agent:
  BASE_IMAGE: dream-agent
  CLUSTER_PORT: 11005
  CMD_SCRIPT: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.channel=telegram agent.telegram_token=$TG_TOKEN agent.pipeline_config=assistant_dists/dream/pipeline_conf.json agent.db_config=assistant_dists/dream/db_conf.json'
  PORT: 11005
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_combined-classification:
  BASE_IMAGE: dream-combined-classification
  CLUSTER_PORT: '8087'
  CMD_SCRIPT:
  - gunicorn
  - --workers=1
  - server:app
  - -b
  - 0.0.0.0:8087
  - --timeout
  - '600'
  CUDA_VISIBLE_DEVICES: 2
  NODE_LIST:
  - gpu9
  PORT: 8087
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_dff-dream-faq-prompted-skill:
  BASE_IMAGE: dream-dff-dream-faq-prompted-skill
  CLUSTER_PORT: '8170'
  CMD_SCRIPT: gunicorn --workers=1 server:app -b 0.0.0.0:8170 --reload --timeout 120
  PORT: 8170
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_dff-dream-persona-chatgpt-prompted-skill:
  BASE_IMAGE: dream-dff-dream-persona-chatgpt-prompted-skill
  CLUSTER_PORT: '8137'
  CMD_SCRIPT: gunicorn --workers=1 server:app -b 0.0.0.0:8137 --reload --timeout 120
  PORT: 8137
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_dff-google-api-skill:
  BASE_IMAGE: dream-dff-google-api-skill
  CLUSTER_PORT: '8162'
  CMD_SCRIPT: gunicorn --workers=1 server:app -b 0.0.0.0:8162
  PORT: 8162
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_dff-intent-responder-skill:
  BASE_IMAGE: dream-dff-intent-responder-skill
  CLUSTER_PORT: '8012'
  CMD_SCRIPT:
  - gunicorn
  - --workers=1
  - server:app
  - -b
  - 0.0.0.0:8012
  - --reload
  PORT: 8012
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_entity-detection:
  BASE_IMAGE: dream-entity-detection
  CLUSTER_PORT: '8103'
  CMD_SCRIPT:
  - flask
  - run
  - -h
  - 0.0.0.0
  - -p
  - '8103'
  CUDA_VISIBLE_DEVICES: 2
  NODE_LIST:
  - gpu9
  PORT: 8103
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_entity-linking:
  BASE_IMAGE: dream-entity-linking
  CLUSTER_PORT: '8075'
  CMD_SCRIPT: gunicorn  --workers=1 --timeout 500 server:app -b 0.0.0.0:8075
  CUDA_VISIBLE_DEVICES: 1
  NODE_LIST:
  - gpu9
  PORT: 8075
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_fact-retrieval:
  BASE_IMAGE: dream-fact-retrieval
  CLUSTER_PORT: '8100'
  CMD_SCRIPT:
  - flask
  - run
  - -h
  - 0.0.0.0
  - -p
  - '8100'
  CUDA_VISIBLE_DEVICES: 1
  NODE_LIST:
  - gpu9
  PORT: 8100
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_factoid-qa:
  BASE_IMAGE: dream-factoid-qa
  CLUSTER_PORT: '8071'
  CMD_SCRIPT:
  - flask
  - run
  - -h
  - 0.0.0.0
  - -p
  - '8071'
  PORT: 8071
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_intent-catcher:
  BASE_IMAGE: dream-intent-catcher
  CLUSTER_PORT: '8014'
  CMD_SCRIPT:
  - python
  - -m
  - flask
  - run
  - -h
  - 0.0.0.0
  - -p
  - '8014'
  CUDA_VISIBLE_DEVICES: 8
  NODE_LIST:
  - gpu9
  PORT: 8014
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_kbqa:
  BASE_IMAGE: dream-kbqa
  CLUSTER_PORT: '8072'
  CMD_SCRIPT:
  - flask
  - run
  - -h
  - 0.0.0.0
  - -p
  - '8072'
  CUDA_VISIBLE_DEVICES: 2
  NODE_LIST:
  - gpu9
  PORT: 8072
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_ner:
  BASE_IMAGE: dream-ner
  CLUSTER_PORT: '8021'
  CMD_SCRIPT:
  - flask
  - run
  - -h
  - 0.0.0.0
  - -p
  - '8021'
  CUDA_VISIBLE_DEVICES: 1
  NODE_LIST:
  - gpu9
  PORT: 8021
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_openai-api-chatgpt:
  BASE_IMAGE: dream-openai-api-chatgpt
  CLUSTER_PORT: '8145'
  CMD_SCRIPT:
  - flask
  - run
  - -h
  - 0.0.0.0
  - -p
  - '8145'
  CUDA_VISIBLE_DEVICES: ''
  PORT: 8145
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_openai-api-chatgpt-16k:
  BASE_IMAGE: dream-openai-api-chatgpt-16k
  CLUSTER_PORT: '8167'
  CMD_SCRIPT:
  - flask
  - run
  - -h
  - 0.0.0.0
  - -p
  - '8167'
  PORT: 8167
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_prompt-selector:
  BASE_IMAGE: dream-prompt-selector
  CLUSTER_PORT: '8135'
  CMD_SCRIPT:
  - flask
  - run
  - -h
  - 0.0.0.0
  - -p
  - '8135'
  PORT: 8135
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_property-extraction:
  BASE_IMAGE: dream-property-extraction
  CLUSTER_PORT: '8136'
  CMD_SCRIPT:
  - flask
  - run
  - -h
  - 0.0.0.0
  - -p
  - '8136'
  PORT: 8136
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_ranking-based-response-selector:
  BASE_IMAGE: dream-ranking-based-response-selector
  CLUSTER_PORT: '8002'
  CMD_SCRIPT:
  - flask
  - run
  - -h
  - 0.0.0.0
  - -p
  - '8002'
  PORT: 8002
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_sentence-ranker:
  BASE_IMAGE: dream-sentence-ranker
  CLUSTER_PORT: '8128'
  CMD_SCRIPT:
  - flask
  - run
  - -h
  - 0.0.0.0
  - -p
  - '8128'
  CUDA_VISIBLE_DEVICES: 9
  NODE_LIST:
  - gpu9
  PORT: 8128
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_sentseg:
  BASE_IMAGE: dream-sentseg
  CLUSTER_PORT: '8011'
  CMD_SCRIPT:
  - flask
  - run
  - -h
  - 0.0.0.0
  - -p
  - '8011'
  PORT: 8011
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_text-qa:
  BASE_IMAGE: dream-text-qa
  CLUSTER_PORT: '8078'
  CMD_SCRIPT:
  - flask
  - run
  - -h
  - 0.0.0.0
  - -p
  - '8078'
  CUDA_VISIBLE_DEVICES: 8
  NODE_LIST:
  - gpu9
  PORT: 8078
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
dream_wiki-parser:
  BASE_IMAGE: dream-wiki-parser
  CLUSTER_PORT: '8077'
  CMD_SCRIPT:
  - flask
  - run
  - -h
  - 0.0.0.0
  - -p
  - '8077'
  CUDA_VISIBLE_DEVICES: ''
  PORT: 8077
  TEMPLATE: socialbot_service
  VERSION_TAG: '1.8'
