dream_ru_entity-detection-ru:
  BASE_IMAGE: dream_ru_entity-detection-ru
  CLUSTER_PORT: 9203
  CMD_SCRIPT: flask run -h 0.0.0.0 -p 9203
  PORT: 9203
  TEMPLATE: socialbot_service
  VERSION_TAG: 0.14.2
dream_ru_ner-ru:
  BASE_IMAGE: dream_ru_ner-ru
  CLUSTER_PORT: 9021
  CMD_SCRIPT: flask run -h 0.0.0.0 -p 9021
  CUDA_VISIBLE_DEVICES: 0
  NODE_LIST:
    - gpu9
  PORT: 9021
  TEMPLATE: socialbot_service
  VERSION_TAG: 0.14.2
dream_ru_dialogrpt-ru:
  BASE_IMAGE: dream_ru_dialogrpt-ru
  CLUSTER_PORT: 9122
  CMD_SCRIPT: flask run -h 0.0.0.0 -p 9122
  CUDA_VISIBLE_DEVICES: 8
  NODE_LIST:
    - gpu9
  PORT: 9122
  TEMPLATE: socialbot_service
  VERSION_TAG: 0.14.2
dream_ru_dialogpt-ru:
  BASE_IMAGE: dream_ru_dialogpt-ru
  CLUSTER_PORT: 9125
  CMD_SCRIPT: flask run -h 0.0.0.0 -p 9125
  CUDA_VISIBLE_DEVICES: 4
  NODE_LIST:
    - gpu9
  PORT: 9125
  TEMPLATE: socialbot_service
  VERSION_TAG: 0.14.2
dream_ru_toxic-classification-ru:
  BASE_IMAGE: dream_ru_toxic-classification-ru
  CLUSTER_PORT: 9126
  CMD_SCRIPT: flask run -h 0.0.0.0 -p 9126
  CUDA_VISIBLE_DEVICES: 2
  NODE_LIST:
    - gpu9
  PORT: 9126
  TEMPLATE: socialbot_service
  VERSION_TAG: 0.14.2
