http_proxy_litinsky:
  TEMPLATE: http_proxy
  CLUSTER_PORT: 7050
  PROXYED_HOST: 192.168.10.221
  PROXYED_PORT: 7050

http_proxy_ignatov:
  TEMPLATE: http_proxy
  CLUSTER_PORT: 7051
  PROXYED_HOST: 192.168.10.78
  PROXYED_PORT: 7051

http_proxy_kuratov:
  TEMPLATE: http_proxy
  CLUSTER_PORT: 7052
  PROXYED_HOST: 192.168.10.129
  PROXYED_PORT: 8337