socialbot_rb:
  TEMPLATE: router_bot
  CLUSTER_PORT: 7069
  CLUSTER_MONGO_PORT: 9098
  CLUSTER_SSH_PORT: 9069
  FB_PAGE_ACCESS_TOKEN: "dummy"
  FB_WEBHOOK_SECRET: "dummy"
socialbot_rbp:
  TEMPLATE: router_bot_poller
  run_flags: ["--agent"]
  run_params:
    --model_url: "http://10.11.1.251:7019/"
    --host: "10.11.1.251"
    --port: "7069"
    --token: "agent_socialbot"
#socialbot_agent:
#  TEMPLATE: socialbot_service
#  BASE_IMAGE: assistant_agent
#  CLUSTER_PORT: 7019
#  CMD_SCRIPT: python -m deeppavlov_agent.run -ch http_client --cors -ul 85918482-3f79-4e16-a278-58191938994c -up 99a31eff-66bf-4663-9968-d21671600195
#  PORT: 4242
socialbot_cobot_topics:
  TEMPLATE: socialbot_service
  BASE_IMAGE: assistant_cobot_topics
  CMD_SCRIPT: python -m deeppavlov riseapi annotators/cobot_topics/cobot_bert.json -p 8001
  CLUSTER_PORT: 8001
  PORT: 8001
dialog_flow_sdk_speech-function-predictor:
  BASE_IMAGE: dialog_flow_sdk_speech-function-predictor
  CLUSTER_PORT: 8107
  CMD_SCRIPT: uvicorn server:app --host 0.0.0.0 --port 8107
  PORT: 8107
  TEMPLATE: socialbot_service
dialog_flow_sdk_speech-function-classifier:
  BASE_IMAGE: dialog_flow_sdk_speech-function-classifier
  CLUSTER_PORT: 8108
  CMD_SCRIPT: uvicorn server:app --host 0.0.0.0 --port 8108
  PORT: 8108
  TEMPLATE: socialbot_service
book_dff-book-skill:
  BASE_IMAGE: book_dff-book-skill
  CLUSTER_PORT: 9032
  CMD_SCRIPT: gunicorn --workers=1 server:app -b 0.0.0.0:9032 --reload
  PORT: 9032
  TEMPLATE: socialbot_service
  SECRET_NAME: "book-secret"
book_agent:
  BASE_IMAGE: book_agent
  CLUSTER_PORT: 9033
  CMD_SCRIPT: python -m deeppavlov_agent.run -ch telegram -pl book_pipeline.json
  PORT: 9033
  TEMPLATE: socialbot_service
  SECRET_NAME: "book-secret"
dreamsfc_speech-function-predictor:
  BASE_IMAGE: dreamsfc_speech-function-predictor
  CLUSTER_PORT: 9107
  CMD_SCRIPT: uvicorn server:app --host 0.0.0.0 --port 9107
  PORT: 9107
  TEMPLATE: socialbot_service
  SECRET_NAME: "dreamsfc-secret"
dreamsfc_speech-function-classifier:
  BASE_IMAGE: dreamsfc_speech-function-classifier
  CLUSTER_PORT: 9108
  CMD_SCRIPT: uvicorn server:app --host 0.0.0.0 --port 9108
  PORT: 9108
  TEMPLATE: socialbot_service
  SECRET_NAME: "dreamsfc-secret"
dreamsfc_dff-book-sfc-skill:
  BASE_IMAGE: dreamsfc_dff-book-sfc-skill
  CLUSTER_PORT: 8034
  CMD_SCRIPT: gunicorn --workers=1 server:app -b 0.0.0.0:8034 --reload
  PORT: 8034
  TEMPLATE: socialbot_service
  SECRET_NAME: "dreamsfc-secret"
dreamsfc_midas-classification:
  CUDA_VISIBLE_DEVICES: 5
  NODE_LIST:
    - gpu9
  BASE_IMAGE: dreamsfc_midas-classification
  CLUSTER_PORT: 9090
  CMD_SCRIPT: flask run -h 0.0.0.0 -p 9090
  PORT: 9090
  TEMPLATE: socialbot_service
  SECRET_NAME: "dreamsfc-secret"
dreamsfc_agent:
  BASE_IMAGE: dreamsfc_agent
  CLUSTER_PORT: 9035
  CMD_SCRIPT: sh -c 'bin/wait && python -m deeppavlov_agent.run -ch telegram -pl sfc_dream.json'
  PORT: 9035
  TEMPLATE: socialbot_service
  SECRET_NAME: "dreamsfc-secret"
ee_agent:
  BASE_IMAGE: entity_extraction_svc_agent
  CLUSTER_PORT: 7040
  CMD_SCRIPT: sh -c 'uvicorn server:app --host 0.0.0.0 --port $PORT --reload'
  PORT: 9999
  TEMPLATE: socialbot_service
  SECRET_NAME: "ee-secret"
  VERSION_TAG: 0.1.12
ee_wiki_parser:
  BASE_IMAGE: entity_extraction_svc_wiki-parser
  CLUSTER_PORT: 9077
  CMD_SCRIPT: sh -c 'flask run -h 0.0.0.0 -p 9077'
  PORT: 9077
  TEMPLATE: socialbot_service
  SECRET_NAME: "ee-secret"
  VERSION_TAG: 0.1.12
ee_entity_extraction:
  BASE_IMAGE: entity_extraction_svc_entity-extraction
  CLUSTER_PORT: 9103
  CMD_SCRIPT: sh -c 'python server.py'
  PORT: 9103
  TEMPLATE: socialbot_service
  SECRET_NAME: "ee-secret"
  VERSION_TAG: 0.1.12
goals_human-goals-detector:
  BASE_IMAGE: goals_human-goals-detector
  CLUSTER_PORT: 8122
  CMD_SCRIPT: flask run -h 0.0.0.0 -p 8122
  PORT: 8122
  TEMPLATE: socialbot_service
  VERSION_TAG: 0.1.7
goals_dff-share-problems-skill:
  BASE_IMAGE: goals_dff-share-problems-skill
  CLUSTER_PORT: 8123
  CMD_SCRIPT: gunicorn --workers=1 server:app -b 0.0.0.0:8123
  PORT: 8123
  TEMPLATE: socialbot_service
  VERSION_TAG: 0.1.7
goals_dff-book-recommendation-skill:
  BASE_IMAGE: goals_dff-book-recommendation-skill
  CLUSTER_PORT: 8124
  CMD_SCRIPT: gunicorn --workers=1 server:app -b 0.0.0.0:8124
  PORT: 8124
  TEMPLATE: socialbot_service
  VERSION_TAG: 0.1.7
goals_dff-series-recommendation-skill:
  BASE_IMAGE: goals_dff-series-recommendation-skill
  CLUSTER_PORT: 8126
  CMD_SCRIPT: gunicorn --workers=1 server:app -b 0.0.0.0:8126
  PORT: 8126
  TEMPLATE: socialbot_service
  VERSION_TAG: 0.1.7
goals_dff-get-book-information-skill:
  BASE_IMAGE: goals_dff-get-book-information-skill
  CLUSTER_PORT: 8127
  CMD_SCRIPT: gunicorn --workers=1 server:app -b 0.0.0.0:8127
  PORT: 8127
  TEMPLATE: socialbot_service
  VERSION_TAG: 0.1.7
goals_dff-test-bot-skill:
  BASE_IMAGE: goals_dff-test-bot-skill
  CLUSTER_PORT: 8128
  CMD_SCRIPT: gunicorn --workers=1 server:app -b 0.0.0.0:8128
  PORT: 8128
  TEMPLATE: socialbot_service
  VERSION_TAG: 0.1.7
goals_dff-travel-recommendation-skill:
  BASE_IMAGE: goals_dff-travel-recommendation-skill
  CLUSTER_PORT: 8129
  CMD_SCRIPT: gunicorn --workers=1 server:app -b 0.0.0.0:8129
  PORT: 8129
  TEMPLATE: socialbot_service
  VERSION_TAG: 0.1.7
goals_dff-have-fun-skill:
  BASE_IMAGE: goals_dff-have-fun-skill
  CLUSTER_PORT: 8130
  CMD_SCRIPT: gunicorn --workers=1 server:app -b 0.0.0.0:8130
  PORT: 8130
  TEMPLATE: socialbot_service
  VERSION_TAG: 0.1.7
goals_goals-tracker:
  BASE_IMAGE: goals_goals-tracker
  CLUSTER_PORT: 8131
  CMD_SCRIPT: flask run -h 0.0.0.0 -p 8131
  PORT: 8131
  TEMPLATE: socialbot_service
  VERSION_TAG: 0.1.7
goals_agent:
  BASE_IMAGE: goals_agent
  CLUSTER_PORT: 11004
  CMD_SCRIPT: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.channel=telegram agent.telegram_token=$TG_TOKEN agent.pipeline_config=assistant_dists/dream/pipeline_conf.json agent.db_config=assistant_dists/dream/db_conf.json'
  PORT: 11004
  TEMPLATE: socialbot_service
  SECRET_NAME: "goal-secret"
  VERSION_TAG: 0.1.7
dream_tg_agent:
  BASE_IMAGE: tg_agent
  CLUSTER_PORT: 11005
  CMD_SCRIPT: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.channel=telegram agent.telegram_token=$TG_TOKEN agent.pipeline_config=assistant_dists/dream/pipeline_conf.json agent.db_config=assistant_dists/dream/db_conf.json'
  PORT: 11005
  TEMPLATE: socialbot_service
  SECRET_NAME: "dream-tg-secret"
  VERSION_TAG: 0.1.6
