socialbot_rb:
  TEMPLATE: router_bot
  CLUSTER_PORT: 7069
  CLUSTER_MONGO_PORT: 9098
  CLUSTER_SSH_PORT: 9069
  FB_PAGE_ACCESS_TOKEN: "dummy"
  FB_WEBHOOK_SECRET: "dummy"
socialbot_rbp:
  TEMPLATE: router_bot_poller
  run_flags: ["--agent"]
  run_params:
    --model_url: "http://10.11.1.251:7019/"
    --host: "10.11.1.251"
    --port: "7069"
    --token: "agent_socialbot"
#socialbot_agent:
#  TEMPLATE: socialbot_service
#  BASE_IMAGE: assistant_agent
#  CLUSTER_PORT: 7019
#  CMD_SCRIPT: python -m deeppavlov_agent.run -ch http_client --cors -ul 85918482-3f79-4e16-a278-58191938994c -up 99a31eff-66bf-4663-9968-d21671600195
#  PORT: 4242
socialbot_cobot_topics:
  TEMPLATE: socialbot_service
  BASE_IMAGE: assistant_cobot_topics
  CMD_SCRIPT: python -m deeppavlov riseapi annotators/cobot_topics/cobot_bert.json -p 8001
  CLUSTER_PORT: 8001
  PORT: 8001
dialog_flow_sdk_speech-function-predictor:
  BASE_IMAGE: dialog_flow_sdk_speech-function-predictor
  CLUSTER_PORT: 8107
  CMD_SCRIPT: uvicorn server:app --host 0.0.0.0 --port 8107
  PORT: 8107
  TEMPLATE: socialbot_service
dialog_flow_sdk_speech-function-classifier:
  BASE_IMAGE: dialog_flow_sdk_speech-function-classifier
  CLUSTER_PORT: 8108
  CMD_SCRIPT: uvicorn server:app --host 0.0.0.0 --port 8108
  PORT: 8108
  TEMPLATE: socialbot_service
ee_agent:
  BASE_IMAGE: entity_extraction_svc_agent
  CLUSTER_PORT: 7040
  CMD_SCRIPT: sh -c 'agent/bin/wait && uvicorn agent.server:app --host 0.0.0.0 --port $PORT --reload'
  PORT: 9999
  TEMPLATE: socialbot_service
  SECRET_NAME: "ee-secret"
  VERSION_TAG: 0.2.0
ee_wiki_parser:
  BASE_IMAGE: entity_extraction_svc_wiki-parser
  CLUSTER_PORT: 9077
  CMD_SCRIPT: sh -c 'flask run -h 0.0.0.0 -p 9077'
  PORT: 9077
  TEMPLATE: socialbot_service
  SECRET_NAME: "ee-secret"
  VERSION_TAG: 0.2.0
ee_entity_extraction:
  BASE_IMAGE: entity_extraction_svc_entity-extraction
  CLUSTER_PORT: 9103
  CMD_SCRIPT: sh -c 'python server.py'
  PORT: 9103
  TEMPLATE: socialbot_service
  SECRET_NAME: "ee-secret"
  VERSION_TAG: 0.2.0
