#!/bin/bash

__root_dir=/.research_spot
__info="
Please enter one of the following commands:

    new <snapshot_name> - to create new snapshot
    activate <snapshot_name> - to activate this snapshot with every container restart
    remove <snapshot_name> - to remove snapshot
    list - to get all available snapshots
    info - go get active snapshot name
    reboot - to restart container
"

__command="$1"
__snapshot="$2"

if [ ! -d "$__root_dir/$USER" ]; then
	mkdir "$__root_dir/$USER"
fi

make_snapshot() {
	if [ "$__snapshot" == "" ]; then
		echo "Please enter snapshot name"
		exit 1
	fi
	mkdir -p "$__root_dir/$USER/snapshots"
	if [ -d "$__root_dir/$USER/snapshots/$__snapshot" ]; then
		echo "Snapshot with '$__snapshot' name is already exists" 
		exit 1
	fi
	cp -a /usr "$__root_dir/$USER/snapshots/$__snapshot"
	echo "Successfully created snapshot '$__snapshot'"
}

activate_snapshot() {
  if [ "$__snapshot" == "" ]; then
    echo "Please enter snapshot name"
    exit 1
  fi
  if [ ! -d "$__root_dir/$USER/snapshots/$__snapshot" ]; then
		echo "Snapshot '$__snapshot' does not exist"
		exit 1
	fi
	echo "$__snapshot" > "$HOME/.restore"
	echo "Snapshot '$__snapshot' is succesfully activated"
	echo "Run 'snapshot reboot' if you want to restart container with this snapshot"
}

load_snapshot() {
  if [ ! -f "/home/$__snapshot/.restore" ]; then
    echo "There is no snapshot to restore"
    exit 0
  fi
  local __sn_name="$(cat /home/$__snapshot/.restore)"
  if [ ! -d "$__root_dir/$__snapshot/snapshots/$__sn_name/." ]; then
    echo "There is no snapshot directory"
    exit 0
  fi
	cp -au "$__root_dir/$__snapshot/snapshots/$__sn_name/." /usr
  echo "Snapshot '$__sn_name' restored"
}

info() {
  if [ ! -f "$HOME/.restore" ]; then
    echo "There is no active snapshot"
    exit 0
  fi
  echo "Active snapshot: $(cat "$HOME/.restore")"
}

list() {
	mkdir -p "$__root_dir/$USER/snapshots"
	local files=$(ls $__root_dir/$USER/snapshots)
	if [ -z "$files" ]; then
		echo "There is no snapshots for $USER"
	else
		echo "There are following snapshots for $USER:"
		echo "$files"
	fi
}

reboot_container () {
  echo "Rebooting container..."
  sudo pkill -f sshd
}

remove() {
	if [ ! -d "$__root_dir/$USER/snapshots/$__snapshot" ]; then
		echo "Snapshot '$__snapshot' does not exist"
		exit 1
	fi
	rm -rf "$__root_dir/$USER/snapshots/$__snapshot"
	echo "Sucessfully removed snapshot '$__snapshot'"
}

case "$__command" in
	new)
		make_snapshot
		;;
	activate)
		activate_snapshot
		;;
	list)
		list
		;;
	remove)
		remove
		;;
  reboot)
    reboot_container
    ;;
  restore)
		load_snapshot
		;;
  info)
    info
    ;;
	*)
		echo "$__info"
		;;
esac
